---
- name: "Configure Relay | Create topology push file"
  template:
    src: "{{ role_path }}/templates/topologyUpdater.sh.j2"
    dest: "{{ cardano_scripts_dir }}/topologyUpdater.sh"
    owner: "{{ server_username }}"
    group: "{{ server_username }}"
    mode: 0704
  tags:
    - configure

- name: "Configure Relay | Create topology pull file"
  template:
    src: "{{ role_path }}/templates/relay_topology_pull.sh.j2"
    dest: "{{ cardano_scripts_dir }}/relay_topology_pull.sh"
    owner: "{{ server_username }}"
    group: "{{ server_username }}"
    mode: 0704
  tags:
    - configure

- name: "Configure Relay | Set topology push update cron"
  ansible.builtin.cron:
    name: "Call topology updater"
    minute: "33"
    job: "{{ cardano_install_dir }}/scripts/topologyUpdater.sh"
  tags:
    - configure
    - crontab

- name: "Configure Relay | Run the topology pull command"
  shell: |
    {{ cardano_scripts_dir }}/relay_topology_pull.sh
  tags:
    - configure
    - always
