---
- name: "Upgrade: all packages"
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: yes
  tags:
    - update

- name: "Upgrade: pull topology file"
  shell: |
    {{ cardano_scripts_dir }}/relay_topology_pull.sh
  when: "'relay-node' in inventory_dir and p2p == true"
  tags:
    - update

- name: "Upgrade: stop cardano-node"
  ansible.builtin.service:
    name: cardano-node
    state: stopped
  when: "'block-producer' in inventory_dir or 'relay-node' in inventory_dir"
  tags:
    - update

- name: "Upgrade: reboot the server"
  ansible.builtin.reboot:
  tags:
    - update
