---
- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
  tags:
    - ssh

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
  tags:
    - ssh

- name: Disable challenge response authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
    state: present
  notify: restart ssh
  tags:
    - ssh

- name: Assign deploy user allowed logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?AllowUsers"
    line: "{{ ssh_allowed_users }}"
    state: present
  notify: restart ssh
  tags:
    - ssh
