---
- name: restart prometheus node exporter
  service:
      name: prometheus-node-exporter
      state: restarted

- name: start cardano-node
  service:
      name: cardano-node
      state: started
